sudo: false
language: python
python: 2.7
services:
  - rabbitmq
  - mongodb
  - elasticsearch
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=lint
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success: coveralls
